"""
A small JSON Schema checker for the subset `schemas.py` emits.

Why this exists rather than `pip install jsonschema`: the schemas here are
generated by one module, use seven keywords between them, and are the last
line of defence on a paid response. A dependency would bring a full draft
implementation, its own error vocabulary and a version to keep current, for a
job that is forty lines.

**Why validate at all when the provider was given the schema?** Because only
one of the three enforces it reliably:

  * Luna's strict Structured Outputs genuinely constrains decoding.
  * Haiku is handed the schema as a tool `input_schema`, which the model treats
    as a strong hint — a well-formed tool call can still omit a key.
  * Qwen's schema becomes a GBNF grammar in llama-server, whose coverage of
    the subset depends on the server build.

And every provider has a text fallback path (`parse_json_loose`) that bypasses
structured output entirely. So "the schema was supplied" is not the same as
"the response matches the schema", and the difference is a `KeyError` deep in
the mobile app rather than a caught failure here.

Supported: `type` (single or nullable union), `properties`, `required`,
`additionalProperties: false`, `items`, `minItems`, `maxItems`, `enum`.
Anything else is ignored — this validates what we generate, not arbitrary
schemas.
"""

from typing import Any, Dict, List

_TYPE_CHECKS = {
    "object": lambda v: isinstance(v, dict),
    "array": lambda v: isinstance(v, list),
    "string": lambda v: isinstance(v, str),
    "boolean": lambda v: isinstance(v, bool),
    # bool is a subclass of int in Python; a boolean where a number belongs is
    # a real mismatch, so it is excluded explicitly.
    "integer": lambda v: isinstance(v, int) and not isinstance(v, bool),
    "number": lambda v: isinstance(v, (int, float)) and not isinstance(v, bool),
    "null": lambda v: v is None,
}


def schema_errors(value: Any, schema: Dict[str, Any], path: str = "$") -> List[str]:
    """Every way `value` fails `schema`, as human-readable paths.

    Returns all failures rather than the first: when a model drops three keys,
    one error at a time turns debugging into three round trips.
    """
    errors: List[str] = []
    if not isinstance(schema, dict):
        return errors

    expected = schema.get("type")
    if expected is not None:
        types = expected if isinstance(expected, list) else [expected]
        if not any(_TYPE_CHECKS.get(t, lambda _v: True)(value) for t in types):
            return ["%s: expected %s, got %s" % (path, "/".join(types), _name(value))]

    if "enum" in schema and value not in schema["enum"]:
        errors.append("%s: %r is not one of %s" % (path, value, schema["enum"]))

    if isinstance(value, dict):
        props = schema.get("properties") or {}
        for key in schema.get("required") or []:
            if key not in value:
                errors.append("%s: missing required key %r" % (path, key))
        if schema.get("additionalProperties") is False:
            for key in value:
                if key not in props:
                    errors.append("%s: unexpected key %r" % (path, key))
        for key, sub in props.items():
            if key in value:
                errors.extend(schema_errors(value[key], sub, "%s.%s" % (path, key)))

    elif isinstance(value, list):
        lo, hi = schema.get("minItems"), schema.get("maxItems")
        if lo is not None and len(value) < lo:
            errors.append("%s: expected at least %d items, got %d" % (path, lo, len(value)))
        if hi is not None and len(value) > hi:
            errors.append("%s: expected at most %d items, got %d" % (path, hi, len(value)))
        item_schema = schema.get("items")
        if isinstance(item_schema, dict):
            for i, item in enumerate(value):
                errors.extend(schema_errors(item, item_schema, "%s[%d]" % (path, i)))

    return errors


def _name(value: Any) -> str:
    return "null" if value is None else type(value).__name__
